### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by victorjoel44** [hskang9/blockchain-javascript#1]
after those two steps? what else? how do i use the post or open the index?

**Comment by victorjoel44** [comment]
post doesnt work, foreach of undefined error

**Comment by hskang9** [comment]
This is because node property of the blockchain object starts with [], which has no element at all. I will add init node array with local address. I forgot to add it there. Thanks for finding error.

**Comment by hskang9** [comment]
I was busy on contributing to ethereum projects. I will set original branch which works(but not perfect) and start working on documentation.
